sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
before_install:
  - gem update --system
  - gem install bundler
  - gem install package_cloud
script:
  - bundle exec fpm-cook -t deb
after_success:
  - package_cloud push miketheman/iperf3/ubuntu/precise /home/travis/build/miketheman/iperf3-package/pkg/iperf3_*_amd64.deb
  - package_cloud push miketheman/iperf3/ubuntu/trusty /home/travis/build/miketheman/iperf3-package/pkg/iperf3_*_amd64.deb
